### ISSUE TITLE
User and developer documentation

### ISSUE THREAD

**Issue by nicl-nno** [ITMO-NSS-team/GEFEST#34]
### Task to obtain mandatory documentation:

- [x] Host in documentation read-the-docs;
- [x] Create quick-start guide;
- [ ] Update readme (in FEDOT-like style);
- [ ] Extend dockstring for major classes;
- [ ] Create extended tutorial for beginners;
- [ ] Create advanced tutorial for developes;

Formal deadline: 01.09.2022
